spring.application.name=backend

spring.profiles.active=prod

logging.level.org.springframework.jdbc=DEBUG
logging.level.com.microsoft.sqlserver.jdbc=DEBUG

# Multipart file upload configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=500MB

server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1

app.jwt.expiration=86400000
app.jwt.secret=1501e6dbf21662fd905e9f48603de60ac38efdc59302c74f6f23a7b34facd4be

# File upload settings (can be overridden by zone-config.properties)
file.upload-dir=uploads
file.base-url=http://localhost